// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AdminDashBoard.Models
{
    [Table("Cart")]
    public partial class Cart
    {
        public Cart()
        {
            Orders = new HashSet<Order>();
            ProductInCarts = new HashSet<ProductInCart>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [Column("UserID")]
        [StringLength(450)]
        public string UserId { get; set; }
        public bool AddedToOrder { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty(nameof(AspNetUser.Carts))]
        public virtual AspNetUser User { get; set; }
        [InverseProperty(nameof(Order.Cart))]
        public virtual ICollection<Order> Orders { get; set; }
        [InverseProperty(nameof(ProductInCart.Cart))]
        public virtual ICollection<ProductInCart> ProductInCarts { get; set; }
    }
}