// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AdminDashBoard.Models
{
    [Table("Order")]
    public partial class Order
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [Column("UserID")]
        [StringLength(450)]
        public string UserId { get; set; }
        [Column("CartID")]
        public int CartId { get; set; }
        public double TotalPrice { get; set; }
        [Column("status")]
        public int Status { get; set; }
        [Required]
        public string Address { get; set; }
        public bool PaymentMethod { get; set; }
        [Required]
        [StringLength(12)]
        public string Phone { get; set; }

        [ForeignKey(nameof(CartId))]
        [InverseProperty("Orders")]
        public virtual Cart Cart { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty(nameof(AspNetUser.Orders))]
        public virtual AspNetUser User { get; set; }
    }
}