// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AdminDashBoard.Models
{
    [Table("Product_In_Cart")]
    public partial class ProductInCart
    {
        [Key]
        [Column("ProductID")]
        public int ProductId { get; set; }
        [Key]
        [Column("CartID")]
        public int CartId { get; set; }
        [Column("quantity")]
        public int Quantity { get; set; }

        [ForeignKey(nameof(CartId))]
        [InverseProperty("ProductInCarts")]
        public virtual Cart Cart { get; set; }
        [ForeignKey(nameof(ProductId))]
        [InverseProperty("ProductInCarts")]
        public virtual Product Product { get; set; }
    }
}